name: material_design_codelab
description: Material Design Codelab for Angulardart
# version: 1.0.0
# homepage: https://www.example.com
# author: Lawrence Tsang <pikalaw@gmail.com>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  angular: ^5.3.1
  angular_components: ^0.13.0
  angular_forms: ^2.1.0
  angular_router: ^2.0.0-alpha+22
  mdc_web:
    git: git@github.com:pikalaw/mdc-web-dart.git

dev_dependencies:
  angular_test: ^2.3.0
  build_runner: ^1.6.0
  build_test: ^0.10.8
  build_web_compilers: ^2.3.0
  pedantic: ^1.8.0
  sass_builder: ^2.0.2
  test: ^1.6.0
